// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace NationalParks.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20220908194632_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NationalParks.Models.NationalPark", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CampingAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ParkFee")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            CampingAllowed = true,
                            Location = "Wyoming USA",
                            Name = "Yellowstone National Park",
                            ParkFee = 25
                        },
                        new
                        {
                            ParkId = 2,
                            CampingAllowed = false,
                            Location = "Arizona USA",
                            Name = "Grand Canyon National Park",
                            ParkFee = 20
                        },
                        new
                        {
                            ParkId = 3,
                            CampingAllowed = false,
                            Location = "South Dakota USA",
                            Name = "Badlands National Park",
                            ParkFee = 35
                        },
                        new
                        {
                            ParkId = 4,
                            CampingAllowed = true,
                            Location = "California USA",
                            Name = "Yosemite National Park",
                            ParkFee = 25
                        },
                        new
                        {
                            ParkId = 5,
                            CampingAllowed = true,
                            Location = "Alaska USA",
                            Name = "Denali National Park",
                            ParkFee = 35
                        },
                        new
                        {
                            ParkId = 6,
                            CampingAllowed = true,
                            Location = "Maine USA",
                            Name = "Acadia National Park",
                            ParkFee = 25
                        },
                        new
                        {
                            ParkId = 7,
                            CampingAllowed = false,
                            Location = "Utah USA",
                            Name = "Arches National Park",
                            ParkFee = 20
                        },
                        new
                        {
                            ParkId = 8,
                            CampingAllowed = true,
                            Location = "Montana USA",
                            Name = "Glacier National Park",
                            ParkFee = 35
                        },
                        new
                        {
                            ParkId = 9,
                            CampingAllowed = true,
                            Location = "Colorado USA",
                            Name = "Grand Teton National Park",
                            ParkFee = 25
                        },
                        new
                        {
                            ParkId = 10,
                            CampingAllowed = true,
                            Location = "Utah USA",
                            Name = "Zion National Park",
                            ParkFee = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
